eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      token: last-civilization
  application:
    name: discovery-service